# Generated by Django 3.2.9 on 2022-08-17 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='Naran')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='Naran')),
                ('pob', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatin Moris')),
                ('dob', models.DateTimeField(blank=True, null=True, verbose_name='Data Moris')),
                ('sex', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=10, null=True, verbose_name='Sexu')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('datetime', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.municipality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
