# Generated by Django 3.2.9 on 2022-08-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220819_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenfermaria',
            name='firstname',
            field=models.CharField(max_length=200, null=True, verbose_name='Naran Propriu'),
        ),
        migrations.AlterField(
            model_name='userenfermaria',
            name='lastname',
            field=models.CharField(max_length=200, null=True, verbose_name='Apelidu'),
        ),
    ]
