# Generated by Django 3.2.9 on 2022-08-19 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enfermaria', '0003_auto_20220819_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=10)),
                ('date_of_response', models.DateField(null=True, verbose_name='Data Pedidu')),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('is_used', models.BooleanField(blank=True, default=False, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('bloodRequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enfermaria.bloodrequest')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_response', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
