# Generated by Django 3.2.9 on 2022-09-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enfermaria', '0005_bloodrequestresponse_doador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequestresponse',
            name='package',
        ),
    ]
