# Generated by Django 3.2.9 on 2022-09-07 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0005_alter_doadorbloodpackage_package'),
        ('enfermaria', '0006_remove_bloodrequestresponse_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestresponse',
            name='doador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doador.doadorbloodpackage'),
        ),
    ]
