# Generated by Django 3.2.9 on 2022-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermaria', '0007_alter_bloodrequestresponse_doador'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_respond',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
