# Generated by Django 3.2.9 on 2022-08-19 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodstock', '0002_bloodstock'),
        ('enfermaria', '0002_bloodrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='Naran Propriu')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='Apelidu')),
                ('sex', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4, null=True)),
                ('date_of_birth', models.DateField(null=True, verbose_name='Data Moris')),
                ('weight', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('pressure', models.CharField(max_length=10)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('bloodGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodstock.bloodgroup')),
                ('enfermaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enfermaria.enfermaria')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
