# Generated by Django 3.2.9 on 2022-08-19 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodstock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='Naran Propriu')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='Apelidu')),
                ('sex', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4, null=True)),
                ('address', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100, null=True)),
                ('pressure', models.CharField(max_length=10)),
                ('package', models.CharField(max_length=25)),
                ('donationdate', models.DateTimeField(null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('bloodGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodstock.bloodgroup')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_substitution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='Naran Propriu')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='Apelidu')),
                ('sex', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4, null=True)),
                ('tinan', models.IntegerField()),
                ('weight', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('pressure', models.CharField(max_length=10)),
                ('package', models.CharField(max_length=10)),
                ('donationdate', models.DateField(blank=True, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('bloodGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodstock.bloodgroup')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_doador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
