# Generated by Django 3.2.9 on 2022-08-19 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bloodstock', '0002_bloodstock'),
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doador',
            name='donationdate',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='package',
        ),
        migrations.RemoveField(
            model_name='doador',
            name='tinan',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='donationdate',
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='package',
        ),
        migrations.AddField(
            model_name='doador',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data Moris'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Data Moris'),
        ),
        migrations.CreateModel(
            name='SubstitutionBloodPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=10)),
                ('donationdate', models.DateField(blank=True, null=True)),
                ('packageStatus', models.CharField(blank=True, choices=[('Banked', 'Banked'), ('Used', 'Used')], default='Banked', max_length=30, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('bloodGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodstock.bloodgroup')),
                ('substitution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doador.substitution')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_substitution_bp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoadorBloodPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=10)),
                ('donationdate', models.DateField(blank=True, null=True)),
                ('packageStatus', models.CharField(blank=True, choices=[('Banked', 'Banked'), ('Used', 'Used')], default='Banked', max_length=30, null=True)),
                ('hashed', models.CharField(max_length=32, null=True)),
                ('bloodGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodstock.bloodgroup')),
                ('doador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doador.doador')),
                ('user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_doador_bp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
