# Generated by Django 3.2.9 on 2022-08-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('doador', '0002_auto_20220819_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='administrativepost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrativepost', to='custom.administrativepost'),
        ),
        migrations.AddField(
            model_name='doador',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doador', verbose_name='Fotografia Doador'),
        ),
        migrations.AddField(
            model_name='doador',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipality', to='custom.municipality'),
        ),
        migrations.AddField(
            model_name='doador',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village', to='custom.village'),
        ),
        migrations.AddField(
            model_name='substitution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='substitution', verbose_name='Fotografia Substitution'),
        ),
    ]
