# Generated by Django 3.2.9 on 2022-08-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('bloodstock', '0002_bloodstock'),
        ('doador', '0003_auto_20220822_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Hela Fatin'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='administrativepost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrativepost', to='custom.administrativepost', verbose_name='Postu Administrativu'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='bloodGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloodstock.bloodgroup', verbose_name='Grupu Ran'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipality', to='custom.municipality', verbose_name='Munisipiu'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='pressure',
            field=models.CharField(max_length=10, verbose_name='Tensaun'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='sex',
            field=models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=4, null=True, verbose_name='Seksu'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village', to='custom.village', verbose_name='Suku'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='weight',
            field=models.CharField(max_length=100, null=True, verbose_name='Todan (KG)'),
        ),
    ]
