# Generated by Django 3.2.9 on 2022-08-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0004_auto_20220822_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadorbloodpackage',
            name='package',
            field=models.IntegerField(null=True, verbose_name='Total Pakote Ran'),
        ),
    ]
